name: Build WebAssembly
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: my-emscripten-docker-image
    steps:
      - uses: actions/checkout@v3
      - name: Build with Emscripten
        run: emcc hello.c -o hello.wasm
